# Generated by Django 3.2.10 on 2023-02-22 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamedate', models.DateField(default=datetime.datetime(2023, 2, 22, 11, 55, 8, 525519), verbose_name='Дата игры')),
                ('p1', models.CharField(max_length=100, verbose_name='Никнейм 1')),
                ('p2', models.CharField(max_length=100, verbose_name='Никнейм 2')),
                ('p3', models.CharField(max_length=100, verbose_name='Никнейм 3')),
                ('p4', models.CharField(max_length=100, verbose_name='Никнейм 4')),
                ('p5', models.CharField(max_length=100, verbose_name='Никнейм 5')),
                ('p6', models.CharField(max_length=100, verbose_name='Никнейм 6')),
                ('p7', models.CharField(max_length=100, verbose_name='Никнейм 7')),
                ('p8', models.CharField(max_length=100, verbose_name='Никнейм 8')),
                ('p9', models.CharField(max_length=100, verbose_name='Никнейм 9')),
                ('p10', models.CharField(max_length=100, verbose_name='Никнейм 10')),
                ('r1', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 1')),
                ('r2', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 2')),
                ('r3', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 3')),
                ('r4', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 4')),
                ('r5', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 5')),
                ('r6', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 6')),
                ('r7', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 7')),
                ('r8', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 8')),
                ('r9', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 9')),
                ('r10', models.CharField(choices=[('maf', 'Мафия'), ('don', 'Дон'), ('ser', 'Шериф'), ('mir', 'Мирный')], default='mir', max_length=3, verbose_name='Роль игрока 10')),
                ('d1', models.FloatField(default=0, verbose_name='Доп игрока 1')),
                ('d2', models.FloatField(default=0, verbose_name='Доп игрока 2')),
                ('d3', models.FloatField(default=0, verbose_name='Доп игрока 3')),
                ('d4', models.FloatField(default=0, verbose_name='Доп игрока 4')),
                ('d5', models.FloatField(default=0, verbose_name='Доп игрока 5')),
                ('d6', models.FloatField(default=0, verbose_name='Доп игрока 6')),
                ('d7', models.FloatField(default=0, verbose_name='Доп игрока 7')),
                ('d8', models.FloatField(default=0, verbose_name='Доп игрока 8')),
                ('d9', models.FloatField(default=0, verbose_name='Доп игрока 9')),
                ('d10', models.FloatField(default=0, verbose_name='Доп игрока 10')),
                ('p_lh', models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='Первоубиенный игрок (номер)')),
                ('lh1', models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='ЛХ 1')),
                ('lh2', models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='ЛХ 2')),
                ('lh3', models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='ЛХ 3')),
                ('winner', models.CharField(choices=[('maf', 'Мафия'), ('mir', 'Мирные')], default='mir', max_length=3, verbose_name='Победившая команда')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Никнейм')),
            ],
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('donwin', models.IntegerField(verbose_name='Дон (вин)')),
                ('donloose', models.IntegerField(verbose_name='Дон (луз)')),
                ('sherifwin', models.IntegerField(verbose_name='Шер (вин)')),
                ('sherifloose', models.IntegerField(verbose_name='Шер (луз)')),
                ('mirwin', models.IntegerField(verbose_name='Мир (вин)')),
                ('mirloose', models.IntegerField(verbose_name='Мир (луз)')),
                ('mafwin', models.IntegerField(verbose_name='Маф (вин)')),
                ('mafloose', models.IntegerField(verbose_name='Маф (луз)')),
                ('dop', models.FloatField(verbose_name='Доп')),
                ('compens', models.FloatField(verbose_name='Компенсация')),
                ('straf', models.FloatField(verbose_name='Штраф')),
                ('twomaf', models.IntegerField(verbose_name='2 черных')),
                ('threemaf', models.IntegerField(verbose_name='3 черных')),
                ('registerdate', models.DateField(default=datetime.datetime(2023, 2, 22, 11, 55, 8, 480384), verbose_name='Дата игры')),
            ],
        ),
    ]
