# Generated by Django 3.2.10 on 2023-02-24 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20, verbose_name='Месяц')),
                ('year', models.IntegerField(default=0, verbose_name='Год')),
                ('date', models.DateField(default='Null', verbose_name='Начало сезона в числовом формате')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 23, 53, 25, 213045), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='registerdate',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 23, 53, 25, 166454), verbose_name='Дата игры'),
        ),
    ]
