# Generated by Django 3.2.10 on 2023-02-28 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230224_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Имя системы')),
                ('password', models.CharField(default=None, max_length=20, verbose_name='Пароль')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 17, 18, 57, 250341), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='registerdate',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 17, 18, 57, 199979), verbose_name='Дата игры'),
        ),
    ]
