# Generated by Django 3.2.18 on 2023-03-15 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230315_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название турнира')),
                ('date', models.DateField(default=datetime.datetime(2023, 3, 15, 16, 0, 10, 75210), verbose_name='Дата проведения турнира')),
                ('selectiongamecounter', models.IntegerField(default=0, verbose_name='Кол-во отборочных игр')),
                ('finalgamecounter', models.IntegerField(default=0, verbose_name='Кол-во финальных игр')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=6, verbose_name='Статус')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 16, 0, 10, 73740), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='registerdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 16, 0, 10, 30324), verbose_name='Дата игры'),
        ),
    ]
