# Generated by Django 3.2.18 on 2023-03-15 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230315_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 16, 3, 7, 669341), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='registerdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 16, 3, 7, 626721), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 16, 3, 7, 670702), verbose_name='Дата проведения турнира'),
        ),
    ]
