# Generated by Django 3.2.18 on 2023-03-21 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230320_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('role', models.CharField(choices=[('player', 'Участник'), ('main referee', 'Главный судья'), ('referee', 'Судья'), ('sideline', 'Боковой')], default='Участник', max_length=20, verbose_name='Роль')),
                ('tournament_id', models.IntegerField(verbose_name='id турнира')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='playercount',
            field=models.IntegerField(default=0, verbose_name='Кол-во игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 10, 21, 11, 516777), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 10, 21, 11, 516795), verbose_name='Дата внесения'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='registerdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 10, 21, 11, 474557), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 10, 21, 11, 518131), verbose_name='Дата проведения турнира'),
        ),
    ]
