# Generated by Django 3.2.18 on 2023-03-21 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230321_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 10, 24, 6, 608014), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 10, 24, 6, 608040), verbose_name='Дата внесения'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='registerdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 10, 24, 6, 555995), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 10, 24, 6, 609659), verbose_name='Дата проведения турнира'),
        ),
    ]
