# Generated by Django 3.2.18 on 2023-03-28 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230322_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiting',
            name='seasonmonth',
            field=models.IntegerField(default=0, verbose_name='Месяц сезона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raiting',
            name='seasonyear',
            field=models.IntegerField(default=0, verbose_name='Год сезона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 16, 37, 24, 677422), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 16, 37, 24, 677444), verbose_name='Дата внесения'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='registerdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 16, 37, 24, 626874), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 16, 37, 24, 678851), verbose_name='Дата проведения турнира'),
        ),
    ]
