# Generated by Django 3.2.18 on 2023-05-04 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230328_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.DeleteModel(
            name='T_Player',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 13, 56, 19, 220964), verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='regdate',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 13, 56, 19, 220980), verbose_name='Дата внесения'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='registerdate',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 13, 56, 19, 220326), verbose_name='Дата игры'),
        ),
    ]
